###### 開発用 ######
x-common-env: &common-env
    TZ: Asia/Tokyo

x-php-env: &php-env
    PHP_MAX_EXECUTION_TIME: 300
    PHP_MEMORY_LIMIT: 128M
    PHP_MAX_INPUT_VARS: 1000
    PHP_POST_MAX_SIZE: 10M
    PHP_UPLOAD_MAX_FILESIZE: 16M

x-db-env: &db-env
    DB_CONNECTION: mysql
    DB_HOST: db
    DB_DATABASE: laravel
    DB_USERNAME: laravel
    DB_PASSWORD: laravel

volumes:
    db-store:

services:
    app:
        build:
            dockerfile: infra/php-apache/docker/development/Dockerfile
            context: .
        working_dir: /work
        ports:
            - 8080:80
        volumes:
            - ./laravel/.env:/work/.env
            - ./laravel/app:/work/app
            - ./laravel/config:/work/config
            - ./laravel/database:/work/database
            - ./laravel/public:/work/public
            - ./laravel/resources:/work/resources
            - ./laravel/routes:/work/routes
            - ./laravel/tests:/work/tests
            - ./laravel/composer.json:/work/composer.json
            - ./laravel/composer.lock:/work/composer.lock
            - ./laravel/vendor:/work/vendor
        environment:
            <<: [*common-env, *php-env, *db-env]
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mysql/mysql-server:8.0
        volumes:
            - ./infra/mysql/my.cnf:/etc/mysql/my.cnf
            - ./infra/mysql/init:/docker-entrypoint-initdb.d
            - db-store:/var/lib/mysql
        ports:
            - 33306:3306
        environment:
            <<: [*common-env]
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        command:
            - mysqld
            - --sql-mode=
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -u root -ppassword | grep 'mysqld is alive'"]
            retries: 30
            timeout: 2s
            interval: 1s
