###### 開発用 ######
x-common-env: &common-env
    TZ: Asia/Tokyo

x-php-env: &php-env
  PHP_MAX_EXECUTION_TIME: 300
  PHP_MEMORY_LIMIT: 128M
  PHP_MAX_INPUT_VARS: 1000
  PHP_POST_MAX_SIZE: 10M
  PHP_UPLOAD_MAX_FILESIZE: 16M

x-redis-env: &redis-env
  SESSION_DRIVER: redis
  REDIS_HOST: redis


services:
  vite:
    build:
      context: .
      dockerfile: ./infra/development/vite/Dockerfile
    volumes:
      - type: bind
        source: ./laravel
        target: /var/www/html
      - type: volume
        source: node_modules
        target: /var/www/html/node_modules
    ports:
      - "5173:5173"
  nginx:
    build: ./infra/development/nginx
    volumes:
      - ./laravel:/var/www/html
      - ./infra/development/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "48080:80"
    app:
        build:
            dockerfile: Dockerfile
            context: .
            args:
                XDEBUG_DISABLED: false
                RELEASE_STAGE: development
                REQUIRE_DEV: true
        working_dir: /work
        ports:
            - 8080:80
        volumes:
            - ./.env:/work/.env
            - ./app:/work/app
            - ./config:/work/config
            - ./database:/work/database
            - ./public:/work/public
            - ./resources:/work/resources
            - ./routes:/work/routes
            - ./tests:/work/tests
            - ./composer.json:/work/composer.json
            - ./composer.lock:/work/composer.lock
            - ./vendor:/work/vendor
        environment:
            <<: [*common-env, *php-env, *db-env, *redis-env]
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
  db:
    build: ./infra/development/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - "43306:3306"
  redis:
      image: redis:7.4.0-alpine
      volumes:
          - ./.docker/redis/data:/data
          - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      command: redis-server /usr/local/etc/redis/redis.conf
      healthcheck:
          test: [ "CMD", "redis-cli", "ping" ]
          retries: 30
          timeout: 2s
          interval: 1s

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/laravel/node_modules
      o: bind
  db-store: